id = "mikrotik-rsc"
name = "MikroTik RouterOS Script"
description = "MikroTik language support for RouterOS (7.22+) with syntax highlighting and command autocompletion."
version = "0.1.0"
schema_version = 1
authors = ["keiras94"]
repository = "https://github.com/keiras94/mikrotik-zed"
categories = ["Languages"]
languages = ["languages/rsc"]

[grammars.rsc]
repository = "https://github.com/rNoz/mikrotik-rsc-grammar"
rev = "18752a43a80e678dece9e2d5cfd26ec9316e4914"

[language_servers.rsc-ls]
name = "MikroTik Language Server"
languages = ["MikroTik Script"]
